version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: hw-db
    environment:
      POSTGRES_DB: hw-db
      POSTGRES_USER: hw-user
      POSTGRES_PASSWORD: bks8RatiyYKWg
    ports:
      - "5432:5432"
    volumes:
      - ./hw-db:/var/lib/postgresql/data

